

name: Database Migration (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ inputs.AWS_ACCOUNT_ID }}:role/GitHubTerraformDeployRole
          aws-region: eu-west-2
      
      - name: Upload migrations to S3
        run: aws s3 sync ./migrations/ s3://db-migrations-${{ inputs.AWS_ACCOUNT_ID }}/migrations/
          
      - name: Invoke migration Lambda
        run: |
          aws lambda invoke \
            --function-name db-migration-runner \
            --payload '{}' \
          response.json